openapi: 3.0.3

info:
  title: 消息推送服务
  description: 消息推送服务

servers:
  - url: /api/v1

paths:
  /publish:
    post:
      summary: 发送消息
      description: 该方法代理 mqtt.publish，详情参见：[MQTT Publish](https://github.com/mqttjs/MQTT.js#mqttclientpublishtopic-message-options-callback)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Publish'
      responses:
        '200':
          description: 发送成功

  /health-check:
    get:
      summary: 服务器状态检查
      responses:
        '200':
          description: 服务器状态正常

  /dev-message:
    get:
      summary: 向 $dev 频道发送系统消息
      responses:
        '200':
          description: 发送成功

    post:
      summary: 向 $dev 频道发送定制消息
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: 发送成功

components:
  schemas:
    Publish:
      type: object
      properties:
        topic:
          type: string
          example: topic/subtopic

        payload:
          type: object
          example: '{ "text": "这是一条消息", "field1": "anything", "field2": "anything", "fieldx": "anything" }'

        options:
          type: object
          example: '{ "qos": 1 }'
